export const GET_FORECAST = "GET_FORECAST";
export const GET_LOCATION = "GET_LOCATION";
export const SET_FORECAST = "SET_FORECAST";
export const SET_CURRENT_WEATHER = "SET_CURRENT_WEATHER";
export const GET_FORECAST2 = "GET_FORECAS2T";
export const SET_FORECAST2 = "SET_FORECAST2";

export const SET_CURRENT_LOCATION = "SET_CURRENT_LOCATION";
